version: '3.4'

services:
  fc.codeflix.catalog.fb:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: COD3fl1X.@

networks:
  default:
    name: service_catalog